### ISSUE TITLE
How does this implementation differ from (tokio-)tungstenite?

### ISSUE THREAD

**Issue by emschwartz** [denoland/fastwebsockets#21]
Faster is always nice :) I'm curious how this implementation differs from [`tokio-tungstenite`](https://github.com/snapview/tokio-tungstenite) and, if it's faster, what different decisions were made that makes it so.

**Comment by nurmohammed840** [comment]
> I'm curious how this implementation differs from [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite)

No code is faster then no code : )
It provide simple implementation which make it [3x faster](https://github.com/nurmohammed840/web-socket-benchmark)

> if it's faster, what different decisions were made that makes it so.

There is no magic! It does two jobs well, encoding frames, and parsing incoming websocket frames.

**Comment by littledivy** [comment]
Just like @nurmohammed840 said, there is no magic. It tries to keep things simple and optimal.

Some key differences from tokio-tungstenite:
- fastwebsockets is fully built on async streams whereas tokio-tungstenite wraps on sync tungnstenite.
- fastwebsockets provides a lower level access to the protocol. You can play around with vectored writes, fragmentation policy, utf-8 validation etc.
- Careful allocations and clone-on-write frame payloads.
