### ISSUE TITLE
Monoio runtime integration

### ISSUE THREAD

**Issue by joeky888** [denoland/fastwebsockets#24]
https://github.com/bytedance/monoio is a new async runtime, it uses epoll for Linux, io_uring for Linux 5.6+, kqueue for macOS/FreeBSD and Windows (Experimental). It should be faster than the tokio runtime.

**Comment by littledivy** [comment]
Interesting, fastwebsockets works with any stream which implements AsyncRead/AsyncWrite.

It should be possible to use fastwebsockets with`monoio-compat` https://github.com/bytedance/monoio/tree/master/monoio-compat

**Comment by joeky888** [comment]
Closed in favor of https://github.com/denoland/fastwebsockets/issues/31.
