### ISSUE TITLE
Plot uWebSockets for public reference

### ISSUE THREAD

**Issue by uNetworkingAB** [denoland/fastwebsockets#26]
Would be good to plot uWebSockets in the graph, for reference since Deno representatives use it in public claims:

> Currently it performs on par with uWebSockets. Sorry for the lack of detailed information, we'll add benchmarks tomorrow.

I downloaded this repo, built it with --release and I got 40-87% that of uWS in the benchmark, esp. at 1 kB messages the difference is major (see graph below).

Sure, it's high up there on 20 byte messages which is good but it's not really there for anything longer than so. Can be a good point of reference to add uWS in benchmarks and increase message sizes to more than 20 bytes. 1 kB is still 1 single TCP packet in most cases. I would be interested in following the gap over time.

**Comment by bartlomieju** [comment]
AFAIK @littledivy is working on that. Out of curiosity, which OS did you bench it on?

**Comment by uNetworkingAB** [comment]
I only benchmark on Linux

**Comment by bartlomieju** [comment]
Cool, thanks!

**Comment by bartlomieju** [comment]
Woah, I just noticed that's my tweet and somehow the tilde I wrote before `on par` is not there. Sorry for the confusion!

**Comment by uNetworkingAB** [comment]
I mean for anything practical it is on par but for nerd comparison and scientific measure it's not. So can be a good thing to track, I'm interested in how things progress, esp. since I've looked at bit at Rust lately. Also interesting to see whenever something io_uring takes over, at that time I need to sit down and tweak a bit.

**Comment by bartlomieju** [comment]
> I mean for anything practical it is on par but for nerd comparison and scientific measure it's not. So can be a good thing to track, I'm interested in how things progress esp. since I've looked at bit at Rust lately.

Agreed.

> Also interesting to see whenever something io_uring takes over, at that time I need to sit down and tweak a bit.

This is something we've been nascently exploring too, but no concrete results yet. Currently we're focusing on squeezing more performance from Tokio on a single thread.

**Comment by uNetworkingAB** [comment]
I did some more testing, if you increase the size of the message echoed to 65k or somewhere around there, the diff increases and becomes very significant:

20k messages/sec with uWS
12k messages/sec with fastwebsockets

Right now I only have MB setting for load_test but should probably lower it to take KB so one can test medium sized messages around 65k-ish

**Comment by uNetworkingAB** [comment]
And for 1 MB is it:

1390
780

**Comment by uNetworkingAB** [comment]
Oh wow! I added KB testing to load_test and testing with 1 KB messages has major difference:

* 320k messages/sec with uWS
* 140k messages/sec with fastwebsockets

**Comment by uNetworkingAB** [comment]
I've found and plotted characteristics above, and made changes to load_test so that it's possible to specify kB message sizes and not just MB. That's how I made the above graph

**Comment by nurmohammed840** [comment]
@uNetworkingAB, Please note that you are not just benchmarking web-socket implementation, 

But rather you are benchmarking  Operating System , Runtime,  Programming language, Interceptor, Compiler, library's  (std, libc)   who knows what else....

What I am saying it that, We really can't benchmark across runtime or languages,

### Example: 

For larger payload you are bancharking (web-socket frame parsing + masking)

Lets say,

`uWebSockets` provide `2x` faster implementation, and finished at `15ms`,
Where `fastwebsockets` finished at `30ms`,

Without any SIMD optimization, both library decode masked payload in `100ms`

So `uWebSockets` finished at `100 + 15 = 115ms`
And `fastwebsockets` finished at `100 + 30 = 130ms`

**Comment by nurmohammed840** [comment]
@uNetworkingAB, If you really want to benchmark against `fastwebsockets`, 

Please provide us two function that encode and decode web-socket frame through FFI, And send us a pull request in this repo ([web-socket-benchmark](https://github.com/nurmohammed840/web-socket-benchmark))

**Comment by littledivy** [comment]
@nurmohammed840 It's good to have and track comparison with uWebSockets. This way we improve the software in general, regardless of implementation details. 

There should be no reason to be 40-50% slower than C++ implementations and should be treated as a bug in most cases.

**Comment by nurmohammed840** [comment]
@littledivy, Is there any room for farther optimization ?

Some possible optimization:

 1. Use SIMD for masking
 2. Avoid separate header encode (so that `fastwebsockets` don't have to rely on `writev`), Try to encode header + payload together.
 3. Avoid use of internal buffering, HTTP, TLS provide ther own internal buffering,

**Comment by uNetworkingAB** [comment]
@nurmohammed840 I literally used the very benchmark that this very repo use. The only thing I did different was to run it over, not only 20 byte messages, but over varying message sizes (20 byte, 1kb, 16kb, 1mb).

**Comment by uNetworkingAB** [comment]
> What I am saying it that, We really can't benchmark across runtime or languages,

The implication of this opinion is totally nuts. Find enough arbitrary distinct characteristics to isolate on, and eventually you have enough isolated comparisons where every project is its own winner in its own isolated echo chamber. I've seen this argument made in the JS camp as well, where rather than improving from reported data, data is denied and shut down based on some failure to categorize the projects in the same pool.

**Comment by uNetworkingAB** [comment]
Focusing on parser performance is quite pointless, it makes no difference. I just ran a parser benchmark of uWS where my 8 year old computer does 63 million 20 byte messages per second per CPU core. Those numbers are quite pointless and say nothing about the server's overall performance. The composition of the server library makes a lot more of a difference, so over focusing on parsers in particular is a dead end, just saying. The parser makes up such a tiny part of the server, esp. for WebSockets where it's not a text format but a very simple binary format.

**Comment by littledivy** [comment]
Just merged a fix, this is what I get with _fastwebsokets_ 0.4.1:

![image](https://user-images.githubusercontent.com/34997667/236452486-23f142d3-f8cf-4ee2-a2a2-339c84302115.png)

![image](https://user-images.githubusercontent.com/34997667/236452210-9623a644-517e-4f56-ad51-083e8c6c0f35.png)

Compile echo_server with 
```
RUSTFLAGS="-C target-cpu=native" cargo build --release --example echo_server
```

There are now charts in `benches/README.md`

**Comment by littledivy** [comment]
Btw I'm using a modified `load_test` that takes a payload size (in bytes)

https://github.com/denoland/fastwebsockets/blob/6bb30ab732fa40d2001986c2f6427fcecede7669/benches/load_test.c

**Comment by uNetworkingAB** [comment]
Nice!

**Comment by uNetworkingAB** [comment]
Btw, I should probably clean up load_test and move to byte size always.
