### ISSUE TITLE
New round of benchmark needed

### ISSUE THREAD

**Issue by uNetworkingAB** [denoland/fastwebsockets#32]
I've fixed the 16kb diff and so this is what I'm getting now. This is with epoll only, ~~master branch~~ v20.42.0.

![1 CPU-core, WebSocket server echoing performance over varying message sizes  higher is better](https://github.com/denoland/fastwebsockets/assets/110806833/1ec40eb5-c5c9-41e2-8353-3986affcd976)

**Comment by uNetworkingAB** [comment]
This is what I'm getting on a Linux 6.0 with v21 (also needs io_uring load_test)

![237968497-05f3acb3-58a6-4a70-ba71-5a01d271cf98](https://github.com/denoland/fastwebsockets/assets/110806833/99adf6b5-fe19-46e2-bf81-e67df6e1e03c)

**Comment by uNetworkingAB** [comment]
....I guess it stopped being fun to keep graphs up to date when it no longer went the way you imagined.

Back to the ol' silent treatment I guess...

**Comment by uNetworkingAB** [comment]
Here's an old graph

![Single-threaded echo performance over varying message sizes, Linux](https://github.com/denoland/fastwebsockets/assets/110806833/7b7f0972-c01c-400b-a91a-c9adb881034b)

**Comment by littledivy** [comment]
There is a [script](https://github.com/denoland/fastwebsockets/blob/main/benches/run.js) that generates the graph - feel free to send a PR.

My priorities have shifted to other things. I don't have time to update graphs every day or two. I will update graphs whenever there is a new fastwebsockets release. If you don't like that, I can remove uWebSockets from the comparison.

**Comment by uNetworkingAB** [comment]
Of course your "priorities have shifted" because it no longer is in your interest to update it any more 😉

**Comment by uNetworkingAB** [comment]
Alright I can probably make a PR with updated numbers some time soon, it will be on another computer, obviously.

**Comment by littledivy** [comment]
Updated
