### ISSUE TITLE
Error: "Invalid status code" when connecting to a wss server

### ISSUE THREAD

**Issue by joeky888** [denoland/fastwebsockets#33]
Hello, is there a working wss client example? Coming from actix-web because [it doesn't support connecting to wss servers](https://github.com/actix/actix-web/issues/1069). This is the code I am using:

```rust
async fn connect(host: &str, path: &str) -> Result<FragmentCollector<Upgraded>> {
    let stream = TcpStream::connect(host).await?;

    let req = Request::builder()
        .method("GET")
        .uri(format!("wss://{}{}", host, path))
        .header("Host", host)
        .header(UPGRADE, "websocket")
        .header(CONNECTION, "upgrade")
        .header(
            "Sec-WebSocket-Key",
            fastwebsockets::handshake::generate_key(),
        )
        .header("Sec-WebSocket-Version", "13")
        .body(Body::empty())?;

    let (ws, _) = fastwebsockets::handshake::client(&SpawnExecutor, req, stream).await?;
    Ok(FragmentCollector::new(ws))
}

let mut ws = connect("fstream.binance.com:443", "/ws/BTCUSDT@markPrice").await?;
ws.write_frame(Frame::text(fastwebsockets::Payload::Borrowed(b"hi"))).await?;
```

And this is what I've got:

```rust
Error: "Invalid status code"
```

And one more question, does this ws client support forward proxies like curl? If so, how to use proxies? Because [tokio-tungstenite doesn't support proxies](https://github.com/snapview/tokio-tungstenite/issues/168).

```fish
curl -x http://localhost:8080 https://google.com
```

Thank you.

**Comment by littledivy** [comment]
You need a client TLS connector. There is an example in the repo for TLS acceptor using rustls https://github.com/denoland/fastwebsockets/blob/main/examples/tls_server.rs

Use a `rustls::TlsConnector` https://docs.rs/tokio-rustls/latest/tokio_rustls/struct.TlsConnector.html or a native_tls connector - anything that implements AsyncRead/AsyncWrite can be passed to fastwebsockets.
