### ISSUE TITLE
Please give an example to connect to websocket url in async way

### ISSUE THREAD

**Issue by ajinkyaraj** [denoland/fastwebsockets#36]
For example like connect_async in tokio-tungstenite. How to use async connect ? 
If some basic knowledge is required to construct such functionality , please guide to appropriate documentation.

**Comment by littledivy** [comment]
Added https://github.com/denoland/fastwebsockets/blob/main/examples/tls_client.rs

**Comment by formbook** [comment]
why does it require such horrendous code to connect to a socket?
