### ISSUE TITLE
Both `read_frame` and `write_frame` are `&mut self`?

### ISSUE THREAD

**Issue by moh-eulith** [denoland/fastwebsockets#39]
Why is read `mut`? How am I supposed to read and write at the same time in a performant way?

Is there some sort of select trickery I'm missing, or is it fundamentally impossible to write if read was called and is waiting on io?

**Comment by littledivy** [comment]
Yes, both read and write need a mutable ref to the underlying I/O because of `AsyncRead`/`AsyncWrite` https://docs.rs/tokio/latest/tokio/io/index.html#asyncread-and-asyncwrite
