### ISSUE TITLE
Add function to split a WebSocket into a read half and a write half

### ISSUE THREAD

**Issue by tyilo** [denoland/fastwebsockets#40]
Related: https://github.com/denoland/fastwebsockets/issues/39

I would like to write to a websocket while waiting for reads in another task.
To accomplish this, I think fastwebsockets should implement something similar to [tokio::net::TcpStream::into_split](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.into_split)

[tokio-tungstenite](https://github.com/snapview/tokio-tungstenite) allows splitting their `WebSocketStream`: https://github.com/snapview/tokio-tungstenite/blob/5dada5d36c7cdd46b8be51354dc65b2136ea6264/examples/client.rs#L32

**Comment by bartlomieju** [comment]
@littledivy please take a look

**Comment by littledivy** [comment]
I am happy to accept PRs that allow spliting into Read and Write streams.

**Comment by peterholak** [comment]
Is this even possible to do (in a performant way) when using a TlsStream?

See e.g. https://github.com/tokio-rs/tls/issues/40, https://github.com/rustls/rustls/issues/288

**Comment by RohanKapurDEV** [comment]
kind of tragic that concurrent reads and writes from a websocket stream are not possible. this seems to shut out a bunch of useful patterns when working with websockets

**Comment by omerbahaar** [comment]
Are you guys working on it?

**Comment by mmastrac** [comment]
The `unstable-split` feature is now in `fastwebsockets` 0.5.0. We _might_ tweak this API in the future but it's going to be shipped in the next version of deno. Feedback on the API is welcome.
