### ISSUE TITLE
Benchmark Clairity

### ISSUE THREAD

**Issue by tryoxiss** [denoland/fastwebsockets#57]
The [benchmark](https://github.com/denoland/fastwebsockets/tree/main/benches) graphs don't have a labled Y-Axis, so it is hard to tell what that is. If its time, then it appears fastwebsockets ir ironically slower. Is it number of packets managed to be sent in some period of time? Even just a note in the page that says "Hey the Y axis is <Thing>" would be useful if editing the graphs are too hard.

**Comment by littledivy** [comment]
Y-axis is the number of messages sent per sec. Added a note in the markdown for now. 

PRs welcome if you want to edit the graph. Chart is created here:
https://github.com/denoland/fastwebsockets/blob/35a1930fdbcdfe9034bb531fcd1690ba9f7737ec/benches/run.js#L101
