### ISSUE TITLE
What about the latest version of handshake?

### ISSUE THREAD

**Issue by 86maid** [denoland/fastwebsockets#58]
I can't find fastwebsockets: in the new version: handshake: : generate_key ()

**Comment by littledivy** [comment]
Are you enabling with the `upgrade` feature?

```toml
fastwebsockets = { version = "0.5", features = ["upgrade"] }
```

**Comment by 86maid** [comment]
Can't he connect directly to wss:// ？？？？？？？

**Comment by 86maid** [comment]
Can only use upgrade, but not connect directly? I am trying to create a websocket client to connect to a websocket server.

**Comment by bartlomieju** [comment]
Here's a full example connecting over TLS https://github.com/denoland/fastwebsockets/blob/main/examples/tls_client.rs

**Comment by 86maid** [comment]
Why not provide the connect function? It's really too cumbersome












xchuang233
***@***.***


---Original---
From: "Bartek ***@***.***&gt;
Date: Fri, Dec 15, 2023 22:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [denoland/fastwebsockets] What about the latest version ofhandshake? (Issue #58)




 
Here's a full example connecting over TLS https://github.com/denoland/fastwebsockets/blob/main/examples/tls_client.rs
