### ISSUE TITLE
Zero unsafe usage

### ISSUE THREAD

**Issue by littledivy** [denoland/fastwebsockets#67]
Eliminate unsafe code and examine dependencies that use it. 

This should have never happened https://github.com/denoland/fastwebsockets/issues/42, my lazy oversight that gone unnoticed in Deno due to single thread usage but impacted other crate users.

**Comment by littledivy** [comment]
https://github.com/denoland/fastwebsockets/blob/70a4a98c3927b400d5db002441788799c9e58846/src/mask.rs#L107

**Comment by radudiaconu0** [comment]
why is htis ocmpleted when the unsafe is still used there?

**Comment by littledivy** [comment]
afaik there is no safe alternative to it without making it slower
