### ISSUE TITLE
Features hidden behind feature flags not shown in docs.rs

### ISSUE THREAD

**Issue by dev-ardi** [denoland/fastwebsockets#71]
you need to enable the things that you want to be documented in `[package.metadata.docs.rs]` in  `Cargo.toml`.

https://docs.rs/about/metadata
https://gist.github.com/mejrs/07e797df984197e464b44aaa7849f3c3

**Comment by littledivy** [comment]
https://github.com/denoland/fastwebsockets/blob/main/Cargo.toml#L85-L87

It's already enabled. I've added axum in `0.7.1`: https://docs.rs/fastwebsockets/0.7.1/fastwebsockets/upgrade/struct.IncomingUpgrade.html
