### ISSUE TITLE
Ext traits should not be used in where bounds

### ISSUE THREAD

**Issue by Darksonn** [denoland/fastwebsockets#73]
The codebase has various where clauses like the following:

https://github.com/denoland/fastwebsockets/blob/5402e4eacdaebd82856e4721151e522bff00e04f/src/fragment.rs#L102-L105

It is recommended that you instead use `S: AsyncRead + AsyncWrite + Unpin`. Functionally they are equivalent, but avoiding the Ext traits makes more sense semantically and produces better error messages for users of your library.

**Comment by littledivy** [comment]
Thanks. Fixed in https://github.com/denoland/fastwebsockets/commit/d2e383348121f98533397c1a096a388f56613e39
