### ISSUE TITLE
`read_frame` may panic

### ISSUE THREAD

**Issue by arBmind** [denoland/fastwebsockets#77]
if `read_frame()` of `Websocket` cannot send ping response because of a socket error it will panic the whole server.

https://github.com/denoland/fastwebsockets/blob/bd38ea52537cd2851813525636a897d826e71ae0/src/lib.rs#L534

The `read_frame()` of `WebSocketRead` seems to try some error conversions, but then panics anyway?

https://github.com/denoland/fastwebsockets/blob/bd38ea52537cd2851813525636a897d826e71ae0/src/lib.rs#L302-L303

This came up in a production environment. I hope this behaviour might be fixed or we will have to use another implementation.

**Comment by littledivy** [comment]
Please provide the panic message or backtrace (with `RUST_BACKTRACE=1`).

**Comment by arBmind** [comment]
Oh, it seems I don't understand Rust. The questionmark is just forwarding the error to the caller. Sorry for the inconvienience!
