### ISSUE TITLE
Benchmark Request : FrameworkBenchmarks

### ISSUE THREAD

**Issue by Malix-off** [denoland/fastwebsockets#86]
It would be very nice to add fastwebsockets to https://www.techempower.com/benchmarks/

See https://github.com/TechEmpower/FrameworkBenchmarks/issues/9207#issuecomment-2294880384

**Comment by littledivy** [comment]
IIRC TechEmpower benchmarks do not measure WebSocket performance, they measure HTTP performance. 

This crate has some of its own [benches](https://github.com/denoland/fastwebsockets/tree/main/benches) which should be easy to add elsewhere.

**Comment by Malix-off** [comment]
https://www.techempower.com/benchmarks/#hw=ph&test=fortune&section=data-r22&l=zik0sf-cn3

uWS is also included in the benchmark

**Comment by littledivy** [comment]
uWS is also an HTTP server, fastwebsockets is not
